version: '3.0.1'

services:
  api:
    build: .
    container_name: 'task-3.0.1'
    ports:
      - '8000:8000'
    env_file: 
      - '/home/raj/Desktop/Day_1_Task/app/.env'
    depends_on:
      - mongodb
    networks:
      - internal_network

  mongodb:
    image: mongo:latest
    container_name: 'mongodb_container'
    volumes:
      - mongo_data:/data
    networks:
      - internal_network

volumes:
  mongo_data:

networks:
  internal_network:
    driver: bridge
    